### ISSUE TITLE
Need a functionality for partial CB frameworks deployment

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-operator#36]
[Problem]

- with operator, we can deploy whole CB frameworks. However, it is hard to deploy CB frameworks selectively.
- For CB framework contributors, a functionality for partial CB frameworks deployment would help having Cloud-barista development environment quickly.
  - For instance, CB-Tumblebug contributors would needs deployed servers for CB-Spider and CB-Dragonfly.

[Suggestion]

- provide a functionality for partial CB frameworks deployment.

**Comment by seokho-son** [comment]
PTAL, @jihoon-seo

**Comment by jihoon-seo** [comment]
PR #40 might enable this feature (for K8s-cluster version).

https://github.com/cloud-barista/cb-operator/pull/40/files#diff-afdf1ca5fa7cfb8294f1aff34da90e54R2

```YAML
cb-dragonfly:
  enabled : true
  service:
    nodePort: 30090
    type: NodePort

cb-restapigw:
  enabled : true
  service:
    nodePort: 30080
    type: NodePort

cb-spider:
  enabled : true
  service:
    nodePort: 31024
    type: NodePort

cb-tumblebug:
  enabled : true
  service:
    nodePort: 31323
    type: NodePort

cb-webtool:
  enabled : true
  service:
    nodePort: 31234
    type: NodePort

```
