### ISSUE TITLE
Need to set the request, limit, livenessProbe, and readinessProbe for CB FWs

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-operator#42]
From @itnpeople:
> 각 프레임워크별 request, limit 에 대한 정의가 필요합니다. 
각 프레임워크별 livenessProbe, readinessProbe 정의가 필요합니다.

**Comment by seokho-son** [comment]
https://kubernetes.io/ko/docs/concepts/workloads/pods/pod-lifecycle/#언제-활성-프로브를-사용해야-하는가
https://kubernetes.io/ko/docs/concepts/workloads/pods/pod-lifecycle/#언제-준비성-프로브를-사용해야-하는가

livenessProbe, readinessProbe의 사용이 꼭 필요한가요?

**Comment by jihoon-seo** [comment]
- 현재 `livenessProbe`는 다음 컨테이너들에 대해 비활성화 되어 있습니다. (주석으로만 존재)
  - cb-spider
  - cb-tumblebug
  - cb-dragonfly
  - cb-webtool
  - cb-restapigw

- 현재 `readinessProbe`는 cb-dragonfly 의 etcd 에 대해서만 다음과 같이 되어 있습니다.
```YAML
etcd:
  enabled: true
  fullnameOverride: "cb-dragonfly-etcd"
  auth:
    rbac:
      enabled: false
  readinessProbe:
    enabled: true
allowNoneAuthentication: true
```

그런데 이 `readinessProbe` 에 대해 Command probe, HTTP probe, TCP probe 중 아무 것도 설정되어 있지 않아서
`readinessProbe` 가 실제로 동작하고 있는지는 모르겠습니다.

---

livenessProbe 와 readinessProbe 의 차이는 다음과 같다고 합니다. (https://bcho.tistory.com/m/1264)
> readinessProbe: 컨테이너의 상태 체크중에 Configuration을 로딩하거나, 많은 데이타를 로딩하거나, 외부 서비스를 호출하는 경우에는 일시적으로 서비스가 불가능한 상태가 될 수 있다. 이런 경우에는 컨테이너를 재시작한다 하더라도 정상적으로 서비스가 불가능할 수 있다. 이런 경우에는 컨테이너를 일시적으로 서비스가 불가능한 상태로 마킹해주면 되는데, 이러한 기능은 쿠버네티스의 서비스와 함께 사용하면 유용하게 이용할 수 있다.

> Liveness probe와 차이점은 Liveness probe는 컨테이너의 상태가 비정상이라고 판단하면, 해당 Pod를 재시작하는데 반해, Readiness probe는 컨테이너가 비정상일 경우에는 해당 Pod를 사용할 수 없음으로 표시하고, 서비스등에서 (일시적으로) 제외한다.

---

현재는, 예를 들어 cb-dragonfly 파드의 상태가 Error 인 경우 자동으로 Restart 하고 있어서,
livenessProbe 를 설정하지 않았는데도 restart 되고 있음을 알 수 있습니다.

---

추후 livenessProbe, readinessProbe 를 정확히 체크하고 그에 따라 적절히 대응하도록 설정해 놓으면
CB-Bridge / cb-operator 의 '장애 복구' 기능을 고도화하는 것으로 볼 수 있겠습니다.

**Comment by seokho-son** [comment]
>추후 livenessProbe, readinessProbe 를 정확히 체크하고 그에 따라 적절히 대응하도록 설정해 놓으면
>CB-Bridge / cb-operator 의 '장애 복구' 기능을 고도화하는 것으로 볼 수 있겠습니다.

@jihoon-seo 동의합니다. 
향후 장애 복구 기능에 대한 작업 스케줄링(우선순위 판단)은 필요해 보이네요.. :)
참고하시기 바랍니다.

**Comment by jihoon-seo** [comment]
Example:
`docker-registry/templates/deployment.yaml`
```yaml
          livenessProbe:
            httpGet:
{{- if .Values.tlsSecretName }}
              scheme: HTTPS
{{- end }}
              path: /
              port: 5000
          readinessProbe:
            httpGet:
{{- if .Values.tlsSecretName }}
              scheme: HTTPS
{{- end }}
              path: /
              port: 5000
```
