### ISSUE TITLE
TODO: Open multiple ports for Spider, Tumblebug, and Dragonfly in Helm chart

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-operator#45]
- Ports for
  - REST
  - gRPC

---

https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
- `.../charts/cb-spider/templates/service.yaml`
- `.../charts/cb-spider/values.yaml`

- `.../charts/cb-tumblebug/templates/service.yaml`
- `.../charts/cb-tumblebug/values.yaml`

**Comment by jihoon-seo** [comment]
[Analysis]

1. In `charts/cb-spider/templates/deployment.yaml`
```YAML
      containers:
        - name: {{ .Chart.Name }}
          #ports:
          #  - name: http
          #    containerPort: 80
          #    protocol: TCP
```

2. In `charts/cb-spider/templates/service.yaml`
```YAML
{{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}  
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: 1024
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
```

3. In `charts/cb-spider/values.yaml`
```YAML
service:
  type: ClusterIP
  port: 1024
```

4. In `values.yaml`
```YAML
cb-spider:
  enabled : true
  service:
    nodePort: 31024
    type: NodePort
```
